//action type de productos 

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const GET_PRODUCT_BY_ID ='GET_PRODUCT_BY_ID';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const GET_CATEGORIES_PRODUCT = 'GET_CATEGORIES_PRODUCT';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
